// <auto-generated />
using System;
using BorrowdungAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BorrowdungAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BorrowdungAPI.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookerEmail");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookerEmail = "budi@pens.ac.id",
                            BookerName = "Budi Santoso",
                            BookerPhone = "081234567890",
                            CreatedAt = new DateTime(2026, 2, 17, 1, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Seminar Teknologi Informasi",
                            RoomId = 1,
                            StartTime = new DateTime(2026, 2, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BookerEmail = "siti@pens.ac.id",
                            BookerName = "Siti Nurhaliza",
                            BookerPhone = "081234567891",
                            CreatedAt = new DateTime(2026, 2, 17, 2, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 2, 21, 15, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Rapat koordinasi proyek",
                            RoomId = 2,
                            StartTime = new DateTime(2026, 2, 21, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("BorrowdungAPI.Models.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang seminar besar dengan proyektor dan sound system",
                            Location = "Gedung A Lantai 1",
                            Name = "Ruang Seminar A",
                            Status = "Tersedia"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang rapat dengan AC dan whiteboard",
                            Location = "Gedung B Lantai 2",
                            Name = "Ruang Rapat B",
                            Status = "Tersedia"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laboratorium komputer dengan 40 unit PC",
                            Location = "Gedung C Lantai 3",
                            Name = "Lab Komputer 1",
                            Status = "Tersedia"
                        });
                });

            modelBuilder.Entity("BorrowdungAPI.Models.Entities.Booking", b =>
                {
                    b.HasOne("BorrowdungAPI.Models.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BorrowdungAPI.Models.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
